site_name: DSA Notes
theme:
  name: material

nav:
  - Home: index.md
  - Array: array.md
  - String: string.md
  - Tree: tree.md
  - Graph: graph.md
  - Dynamic Programming: dynamic-programming.md
  - Stack: stack.md
  - Queue: queue.md
  - Linked List: linked-list.md
  - Trie: trie.md
  - Maths: maths.md
  - Bit Manipulation: bit-manipulation.md
  - Greedy Algorithm: greedy.md